[package]
name = "rustpass"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.27", features = ["derive"] }
protobuf = "3.7.1"

[build-dependencies]
protobuf-codegen = "3.7.1"
